[macro]
rho = 0.06 # discount
eta = 1.5 
GDP_output_2017 = 7803.40e6 # [US$] from Penn World Tables
k_stock_2017 = 51194.09e6 # [US$] from Penn World Tables
pi = 0.15242775093765706  # average productivity of assets
extreme_poverty_line = 265.29 # per month/per capita in SRD
poverty_line = 733.10 # per month/per capita in SRD