[macro]
pi= 0.4910 # = 83541 / 170129  average productivity
rho = 0.1267 # 12.67 / 100  discount rate
#rho = 0.06 # used by Bramka
eta = 1.5  # elasticity of the marginal utility
gdp = 22217  # gdp per capita in 2016 in BS
extremepoverty = 395.3 # [Bs] per month
poverty = 804.8  # [Bs] per month
gamma = 1.2  # equity weight
hh = 2.3  # equivalent household determined empirically

[income] # inc / hh / month
INE = 4234   # INE
JICA = 4257  # encuesta JICA

[bbox]  # bbox data available in FIAT
xmin = -63.26
xmax = -63.05
ymin = -17.9
ymax = -17.65

