[macro]
pi= 0.4910 # = 83541 / 170129  average productivity
rho = 0.1267 # 12.67 / 100  discount rate
#rho = 0.06 # used by Bramka
eta = 1.5  # elasticity of the marginal utility
gdp = 22217  # gdp per capita in 2016 in BS
extremepoverty = 395.3 # [Bs] per month
poverty = 804.8  # [Bs] per month