[macro]
pi= 0.4910 # = 83541 / 170129  average productivity
rho = 0.1267 # 12.67 / 100  discount rate
eta = 1.5
gdp = 22217  # gdp per capita in 2016 in BS
extremepoverty = 395.3 # [Bs] per month
poverty = 804.8  # [Bs] per month