[macro]
pi = 0.4910 # = 83541 / 170129  average productivity  = output-side real GDP / capital stock from PWT
rho = 0.1267 # 12.67 / 100  discount rate from J. A. Rueda-Gallardo 2020 (find one corresponding to 2016)
eta = 1.5  # elasticity in line with Hallegatte et al 2016 and Walsh and Hallegatte 2019
gdp = 22217  # gdp per capita in 2016 in BS
gamma = 1.5 # equity weight
extremepoverty = 395.3 # [Bs] per month. per hh or per capita?
poverty = 804.8  # [Bs] per month. per hh or per capita?
hh = 2.3 # determined empirically people or equivalent adult per household

[income]
JICA = 4257 # avg income/month/hh
INE = 4234  # avg income/month/hh
innerring = 4259 # avg income/month/hh computed in the inner ring

[fiat]
# fraction affected by return period from FIAT output
f2 = 0.016
f10 = 0.039

[bbox]
# bounding box to exclude area where fiat results not available
xmin = -63.26
xmax = -63.05
ymin = -17.9
ymax = -17.65
